Repository pesto-students/batch-8-CODERHOOD, pull requests merged in 2019-07, with the labels that each got.

#77 Fix(socket): Add check for workspace when loading a conversation
  client/src/containers/Workspace/Workspace.js
  client/src/containers/Workspace/utils.js
  server/src/Controller/Message/MessageController.js
Labels: bug

#97 chore: Add yarn.lock files and netlify _redirects
  client/_redirects
  client/yarn.lock
  server/yarn.lock
Labels: Setup

#101 Feat (Typing-indicator): Add real time typing indicator to chats.
  client/src/constants/constants.js
  client/src/containers/Workspace/Workspace.js
  server/src/Sockets/events.js
  server/src/Sockets/socket.js
Labels: feature request
